version: "3.3"
services:
 jenkins:
  image: jenkins/jenkins:lts-alpine
  volumes:
   - jenkins_home:/var/jenkins_home
  deploy:
   replicas: 1
   restart_policy:
    condition: any
  ports:
   - "8080:8080"
volumes:
 jenkins_home:
