version: "3"
services:
    php:
      image: secobau/php:apache
      networks:
        - frontend
      deploy:
        replicas: 3
        restart_policy:
          condition: on-failure
      ports:
        - 80:80
      labels:
        - "com.docker.lb.sticky_session_cookie=session"
networks:
    frontend:
