version: "3"
services:
    php:
      image: secobau/php:basic
      networks:
        - frontend
      deploy:
        replicas: 11
        restart_policy:
          condition: on-failure
      ports:
        - 80:80
networks:
    frontend:
