version: "3.3"
services:
  php:
    image: secobau/php:apache
    networks:
      - frontend
    deploy:
      replicas: 4
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: "0.06"
          memory: 60M
    ports:
      - "8080:80"
networks:
  frontend:
