version: '3.3'
services:
 web:
  image: "xwiki:mysql-tomcat"
  ports:
   - "8080:8080"
  environment:
   - DB_USER=xwiki
   - DB_PASSWORD=xwiki
   - DB_DATABASE=xwiki
   - DB_HOST=db
  volumes:
   - xwiki-data:/usr/local/xwiki
  #secrets:
   #- xwiki-db-username
   #- xwiki-db-password
 db:
  image: "mysql:5.7"
  volumes:
   - mysql-data:/var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=xwiki
   - MYSQL_USER=xwiki
   - MYSQL_PASSWORD=xwiki
   - MYSQL_DATABASE=xwiki
  #secrets:
   #- xwiki-db-username
   #- xwiki-db-password
   #- xwiki-db-root-password
  #configs: 
   #- source: mysql-config
   #- target: /etc/mysql/conf.d/xwiki.cnf
volumes:
 mysql-data:
 xwiki-data:
#secrets:
 #xwiki-db-username:
  #external:
   #name: xwiki-db-username
 #xwiki-db-password:
  #external:
   #name: xwiki-db-password
 #xwiki-db-root-password:
  #external:
   #name: xwiki-db-root-password
#configs:
 #mysql-config:
  #external:
   #name: xwiki-mysql-config
#echo ${MY_XWIKI_USER:-xwiki} | docker secret create xwiki-db-username -
#echo $(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1) | docker secret create xwiki-db-password -
#echo $(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1) | docker secret create xwiki-db-root-password -
#docker config create xwiki-mysql-config /path/to/mysql/xwiki.cnf
