version: "3.7"
services:
  php:
    image: secobau/php:apache
    networks:
      - frontend
    deploy:
      replicas: 33
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M          
    ports:
      - "8080:80"
networks:
  frontend:
