version: "3.7"
services:
  php:
    image: secobau/php:apache
    networks:
      - frontend
    deploy:
      replicas: 99
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: "0.50"
          memory: 2048M
        reservations:
          cpus: "0.25"
          memory: 1024M
    ports:
      - "8080:80"
networks:
  frontend:
