version: "3.7"
services:
  php:
    image: secobau/php:apache
    networks:
      - frontend
    deploy:
      replicas: 3
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == worker
      resources:
        limits:
          cpus: "0.06"
          memory: 60M
        reservations:
          cpus: "0.02"
          memory: 20M          
    ports:
      - "8080:80"
networks:
  frontend:
