version: "3"
services:
    php:
      image: secobau/php:apache
      networks:
        - frontend
      deploy:
        replicas: 126
        restart_policy:
          condition: on-failure
      ports:
        - 80:80
networks:
    frontend:
